# https://taskfile.dev

version: '3'

vars:
  PKGS:
    sh: find . -name PKGBUILD -exec dirname {} \; | xargs -n1 basename

tasks:

  checknew:
    desc: Check for outdated versions
    dir: pkgs
    cmds:
      - bash ./check_update.sh

  buildpkg:
    label: build-{{.PKG}}
    sources:
      - pkgs/{{.PKG}}/PKGBUILD
    generates:
      - pkgs/{{.PKG}}/*.deb
    cmds:
      - |
        (
          cd ./pkgs/{{.PKG}}
          makedeb
        )

  buildall:
    desc: Build all packages
    cmds:
      - |
        for i in {{.PKGS | catLines}}; do
          task buildpkg "PKG=$i"
        done

  clean:
    desc: Clean all but deb files
    cmds:
      - git clean -f -d -x -e '*.deb' -e '.task/*'

  cleanall:
    desc: Clean everything incl deb files
    cmds:
      - git clean -f -d -x -e '.task/*'

  uploadall:
    desc: Upload all found packages into gcloud
    cmds:
      - |
        find . -type f -name '*.deb' -print0 | xargs -0 -n1 bash pkgs/upload_pkg.sh

  upload:
    desc: Upload single package
    cmds:
      - bash pkgs/upload_pkg.sh {{.CLI_ARGS}}
